name: Deploy Sample Node App to Scaleway

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy to Scaleway Serverless Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Scaleway CLI
        uses: scaleway/action-scw@v0
        id: configure-scw
        with:
          save-config: true
          export-config: true
          version: v2.24.0
          region: ${{ secrets.SCW_REGION }}
          registry: ${{ secrets.SCW_REGISTRY }}
          repository: ${{ secrets.SCW_REPOSITORY }}
          service: sample-node-app
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          container-id: ${{ secrets.SCW_CONTAINER_ID }}

      - name: Login to Scaleway Container Registry
        run: |
          echo "${{ secrets.SCW_SECRET_KEY }}" | docker login ${{ secrets.SCW_REGISTRY }} -u nologin --password-stdin

      - name: Build and push Docker image with unique tag
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE=${{ secrets.SCW_REGISTRY }}/sample-node-ns/sample-node-app:$IMAGE_TAG
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Scaleway Serverless Container
        run: |
          source $GITHUB_ENV
          scw container container update ${{ secrets.SCW_CONTAINER_ID }} registry-image=$IMAGE
          scw container container deploy ${{ secrets.SCW_CONTAINER_ID }}
