name: Deploy Sample Node App to Scaleway

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy to Scaleway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Scaleway credentials
        uses: scaleway/action-scw@v0
        id: configure-scw
        with:
          save-config: true
          export-config: true
          version: v2.24.0
          region: ${{ secrets.SCW_REGION }}
          registry: ${{ secrets.SCW_REGISTRY }}
          repository: ${{ secrets.SCW_REPOSITORY }}
          service: sample-node-app
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          container-id: ${{ secrets.SCW_CONTAINER_ID }}

      - name: Login to Scaleway Container Registry
        run: |
          echo "${{ secrets.SCW_SECRET_KEY }}" | docker login ${{ secrets.SCW_REGISTRY }} -u nologin --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.SCW_REGISTRY }}/${{ secrets.SCW_REPOSITORY }}:$IMAGE_TAG \
                       -t ${{ secrets.SCW_REGISTRY }}/${{ secrets.SCW_REPOSITORY }}:latest .
          docker push ${{ secrets.SCW_REGISTRY }}/${{ secrets.SCW_REPOSITORY }}:$IMAGE_TAG
          docker push ${{ secrets.SCW_REGISTRY }}/${{ secrets.SCW_REPOSITORY }}:latest
          echo "IMAGE=${{ secrets.SCW_REGISTRY }}/${{ secrets.SCW_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: SSH and deploy new container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop sample-node-app || true
            docker rm sample-node-app || true
            docker pull $IMAGE
            docker run -d -p 3000:3000 --name sample-node-app $IMAGE
